-- CREATE DEPT TABLE

CREATE TABLE DEPT
(
    DNO VARCHAR2(3) PRIMARY KEY CHECK(DNO LIKE 'D%'),
    DNAME VARCHAR2(10) UNIQUE
);

DESC DEPT;
SELECT * FROM DEPT;

-- CREATE PROJECTS TABLE

CREATE TABLE PROJECTS
(
    DNO VARCHAR2(3) REFERENCES DEPT NOT NULL,
    PRJ_NO VARCHAR2(5) CHECK(PRJ_NO LIKE 'P%') NOT NULL,
    PRJ_NAME VARCHAR2(10),
    PRJ_CREDITS NUMBER(2) CHECK(PRJ_CREDITS BETWEEN 1 AND 10),
    START_DATE DATE,
    END_DATE DATE,
    CHECK(END_DATE > START_DATE),
    PRIMARY KEY (DNO,PRJ_NO)
);

DESC PROJECTS;
SELECT * FROM PROJECTS;


-- CREATE EMP TABLE

CREATE TABLE EMP
(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    EJOB VARCHAR2(9) CHECK(EJOB IN('CLRK','MGR','A.MGR','GM','CEO')) DEFAULT 'CLRK',
    MGR_ID NUMBER(4),
    BIRTH_DATE DATE, 
    SAL NUMBER(7,2) CHECK(SAL > 20000) DEFAULT 20001,
    COMM NUMBER(7,2) DEFAULT 1000,
    DEPTNO VARCHAR2(3) REFERENCES DEPT,
    PRJ_ID VARCHAR2(9) CHECK(PRJ_ID IN('CLRK','MGR','A.MGR','GM','CEO')) DEFAULT 'CLRK',
    DATE_OF_JOIN DATE,
    CHECK(BIRTH_DATE < DATE_OF_JOIN)
);

DESC EMP;
SELECT * FROM EMP;

